development:
  adapter: postgresql
  database: read_crowd_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: read_crowd_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: read_crowd_production
  pool: 5
  timeout: 5000
